stages:
  clean_data:
    cmd: python src/data_process/clean_data.py
    deps:
      - src/data_process/clean_data.py
    outs:
      - data/processed/MITRE/mitre_cleaned.parquet
      - data/processed/sigma/sigma_cleaned.parquet
      - data/processed/emerging_threats/et_rules_cleaned.parquet

  ingest_kb:
    cmd: python src/data_process/ingest_kb.py
    deps:
      - src/data_process/ingest_kb.py
      - data/kb/port_profile/port_profiles.jsonl
      - data/kb/conn_state/conn_state_profiles.jsonl
      - data/kb/traffic_pattern/traffic_pattern_profiles.jsonl
      - data/kb/tactic_profile/tactic_profiles.jsonl
      - data/kb/suricata_category/suricata_category_profiles.jsonl
    params:
      - embedding.model_name
      - embedding.dim
      - embedding.batch_size
    outs:
      - data/kb/ingest_completed.txt