stages:
  clean_data:
    cmd: python src/data_process/clean_data.py
    deps:
      - src/data_process/clean_data.py
    outs:
      - data/processed/MITRE/mitre_cleaned.parquet
      - data/processed/sigma/sigma_cleaned.parquet
      - data/processed/emerging_threats/et_rules_cleaned.parquet
      - data/processed/behavioral_rules/chunks.parquet

  chunk_data:
    cmd: python src/data_process/chunk_data.py
    deps:
      - src/data_process/chunk_data.py
      - data/processed/MITRE/mitre_cleaned.parquet
      - data/processed/sigma/sigma_cleaned.parquet
      - data/processed/emerging_threats/et_rules_cleaned.parquet
    params:
      - chunking.tokenizer_model
      - chunking.chunk_size
      - chunking.chunk_overlap
    outs:
      - data/processed/MITRE/chunks.parquet
      - data/processed/sigma/chunks.parquet
      - data/processed/emerging_threats/chunks.parquet

  embed_chunks:
    cmd: python src/data_process/embed_chunks.py --recreate
    deps:
      - src/data_process/embed_chunks.py
      - data/processed/MITRE/chunks.parquet
      - data/processed/sigma/chunks.parquet
      - data/processed/emerging_threats/chunks.parquet
      - data/processed/behavioral_rules/chunks.parquet
    params:
      - embedding.model_name
      - embedding.dim
    outs:
      - data/embeddings/completed.txt