from prometheus_client import Counter, Histogram, make_asgi_app, Gauge
import time
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request

# ── Metrics definitions ──────────────────────────────────────────────────────

REQUEST_COUNT = Counter(
    "rag_request_total",
    "Total HTTP requests",
    ["endpoint", "status_code"],
)

REQUEST_LATENCY = Histogram(
    "rag_request_duration_seconds",
    "HTTP request latency (full round-trip)",
    ["endpoint"],
    buckets=[0.5, 1, 2, 4, 8, 16, 30, 60],
)


LLM_TOKENS_PER_SECOND = Histogram(
    "rag_llm_tokens_per_second",
    "LLM generation speed (tokens/second)",
    buckets=[5, 10, 20, 30, 50, 80, 120, 200],
)

LLM_TOKENS_GENERATED = Counter(
    "rag_llm_tokens_generated_total",
    "Total tokens generated by LLM",
)

# ── HTTP middleware ───────────────────────────────────────────────────────────

class PrometheusMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        start = time.perf_counter()
        status_code = 500
        try:
            response = await call_next(request)
            status_code = response.status_code
            return response
        finally:
            # Use the route template (e.g. "/chat/{session_id}") instead of the
            # raw path so dynamic params don't explode label cardinality.
            route = request.scope.get("route")
            endpoint = getattr(route, "path", request.url.path)
            duration = time.perf_counter() - start

            REQUEST_LATENCY.labels(endpoint=endpoint).observe(duration)
            REQUEST_COUNT.labels(
                endpoint=endpoint,
                status_code=str(status_code),
            ).inc()


# ASGI app that serves /metrics
metrics_app = make_asgi_app()
